### PR TITLE
Fixing the ymd date format.

### PR DESCRIPTION
**Pull request by bc238dev**
Exported file name was like "journalbook_201903.json" so the date format was wrong. I just fixed that.

### CODE REVIEW

**Comment by trys** [comment]
Awesome - thank you! Sadly this has ✨  _implications_  ✨  with existing entry keys, as I stupidly missed this from the offset, such a rookie mistake 🙃 I've literally been fighting this exact problem this evening and was wondering whether dealing with it properly could be put off - alas not :joy:

So, I think there'll need to be a 'migration' of existing entry keys from `201903` to `20190103` done on app startup. It ain't gonna be pretty, but I guess now's the time to do it! Here lies the issue with not having a centralised server of data that can be easily patched!

I've got a pretty good idea on what to update, so if it's okay, I'll pull down this PR and write the migration and it can all go live together.

**Comment by trys** [comment]
Here we go! I'll run some tests on the Netlify dev environment and we'll see what happens!

**Comment by trys** [comment]
Right, I think it's all good. Here goes 🤞

**Comment by bc238dev** [comment]
Awesome :)

**Pull request merged**
